### ISSUE TITLE
npmignore benchmark.html 

### ISSUE THREAD

**Issue by mukundha** [pvdz/ZeParser#18] opened 2013-06-08 17:17 UTC
Hello,

can  benchmark.html (8mb) be added to .npmignore, this will greatly help reduce the size of the apps using this module

thanks,

**Comment by pvdz** [comment] 2013-06-10 09:18
That file should be ignored by the `*.html` rule in the current `.npmignore`. Isn't it?

**Comment by felixrabe** [comment] 2013-06-17 19:27
It is. Probably a dependant package has an explicit dependency on an older version. Cf. #19. @mukundha can you verify which package uses the old zeparser version?

**Comment by pvdz** [comment] 2013-06-19 07:15
This is a dupe of #19

**Closed as completed by pvdz** 2013-06-19 07:15 UTC
